POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "wanderley santos",
  "email": "wandercom",
  "password": "psod"
}
###

GET http://localhost:3333/users
###

POST http://localhost:3333/users/login
Content-Type: application/json

{
  "email": "wander@gmail.com",
  "password": "password"
}
###

POST http://localhost:3344/games/
Content-Type: application/json

{
  "name": "Starfield",
  "key": "wander12@gmail.com",
  "img": "https://images.app.goo.gl/ENuaireptdKdbR1w8"
}
###

POST http://localhost:3333/user-game
Content-Type: application/json

{
  "userId": 2,
  "gameId": 1,
  "endDate": "2023-11-16 18:58:00.427165+00"
}
###

