POST http://localhost:3344/users
Content-Type: application/json

{
  "name": "wanderley santos",
  "email": "wandercom",
  "password": "psod"
}
###

GET http://localhost:3344/users
###

POST http://localhost:3344/auth/login
Content-Type: application/json

{
  "email": "wander@gmail.com",
  "password": "password"
}
###

POST http://localhost:3344/games/
Content-Type: application/json

{
  "name": "Starfield",
  "key": "wander12@gmail.com",
  "img": "https://images.app.goo.gl/ENuaireptdKdbR1w8"
}
###

GET  http://localhost:3344/games/not-rented
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhbmRlckBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMDUyODcwMSwiZXhwIjoxNzAwNTI4OTAxfQ.Os5e6lu1Kc9J36qyZwHUmjZCI4qrpazFtxaDP6IU2LE
###

POST http://localhost:3344/user-game
Content-Type: application/json

{
  "userId": 2,
  "gameId": 1,
  "endDate": "2023-11-16 18:58:00.427165+00"
}
###

