POST http://localhost:3344/users
Content-Type: application/json

{
  "name": "wanderley santos",
  "email": "wandercom",
  "password": "psod"
}
###

GET http://localhost:3344/users
###

POST http://localhost:3344/auth/login
Content-Type: application/json

{
  "email": "wander@gmail.com",
  "password": "password"
}
###
GET  http://localhost:3344/games/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhbmRlckBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTYyNjQ0NiwiZXhwIjoxNzAxNjI3NDQ2fQ.SbaWPVY9OsUVwZI0dyBPvtX9fwHAMaUdb3HLD_P8VJE
###

POST http://localhost:3344/user-game
Content-Type: application/json

{
  "userId": 2,
  "gameId": 1,
  "endDate": "2023-11-16 18:58:00.427165+00"
}
###

